name: login_page_design
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.3.2
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  fluttertoast: ^8.0.7
  flutter_screenutil: ^5.1.1
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  full_screen_image: ^1.0.2
  flutter_signin_button: ^2.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/Logo.png
      - assets/images/download.jpg
      
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
